name: BigQuery data
on:
  repository_dispatch:
    types: [bigquery-build]
  schedule:
    - cron: '15 1 * * *'

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout build repo
        uses: actions/checkout@v2
        with:
          path: ./

      - name: Checkout data repo
        uses: actions/checkout@v2
        with:
          ref: 'data'
          path: ./_data

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: yarn install

      - name: Build data files
        env:
          BIGQUERY_CREDENTIALS: ${{ secrets.BIGQUERY_CREDENTIALS }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          yarn build:bigquery

      - name: Commit data files
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update data data
          repository: ./_data
          file_pattern: ./**
          commit_author: COVID Tracking Project Web Data Builder <accounts@covidtracking.com>

      - name: Prepare artifacts
        run: |
          rm -rf ./_data/.git
          tar -czvf data-files.tar.gz ./_data

      - name: Upload data artifacts
        uses: actions/upload-artifact@v2
        with:
          name: data-files
          path: ./data-files.tar.gz
